name: Compress and Deploy to Cloudflare

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Minifiers
        run: |
          npm install -g html-minifier terser clean-css-cli

      - name: Prepare dist folder
        run: |
          mkdir dist
          cp index.html dist/
          cp -r styles dist/styles
          cp -r scripts dist/scripts

      - name: Minify HTML
        run: |
          html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true dist/index.html -o dist/index.html

      - name: Minify CSS
        run: |
          for file in $(find dist/styles -name "*.css"); do
            cleancss -o "$file" "$file"
          done

      - name: Minify JS
        run: |
          for file in $(find dist/scripts -name "*.js"); do
            terser "$file" -o "$file" -c -m
          done

      - name: Push to cf-pages branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan cf-pages
          git rm -rf .
          cp -r dist/* .
          git add .
          git commit -m "Compressed build $(date)"
          git push -f origin cf-pages

      - name: Trigger Cloudflare Deploy Hook
        run: |
          curl -X POST "${{ secrets.CF_DEPLOY_HOOK_URL }}"